# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  only:
      - master
      
# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

environment:
  SONAR_TOKEN:
    secure: 5c958f8a4c9b6ebf9a2e5b90a38ab9e6bcadd191
  GITHUB_SONAR_TOKEN:
    secure: 
    
# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config

services:
  - mysql2017
  
  build_script:
- ps: >-
    cd .\build
    .\build.ps1


test: off
